name: thesis_no_gpu
channels:
  - conda-forge
  - pkgs/main
  - defaults
dependencies:
  - python
  - tensorflow=2.10.0
  - tensorflow-datasets
  - tensorflow-probability
  - numpy
  - matplotlib
  - tqdm
  - pandas
  - scikit-learn
  - scipy=1.12.0
  - seaborn
  - ipykernel  
